version: "3.5"
services:
  monero.dnp.dappnode.eth:
    build: ./build
    image: "monero.dnp.dappnode.eth:0.2.3"
    ports:
      - "18080:18080"
    volumes:
      - "data:/root/.bitmonero"
    environment:
      - EXTRA_FLAGS=
volumes:
  data: {}
